/**
 * @file repositories.ts
 * @brief Repository contracts. Services depend on these, never on SQL.
 */
import type {
	ApiTokenRow,
	CommentRow,
	CommentStatus,
	PageViewRow,
	PostRow,
	RevisionRow,
	SessionRow,
	SubscriberRow,
	TagRow,
	TokenScope,
	UserRow
} from './schema.js';

/**
 * @brief User persistence contract.
 */
export interface UserRepository {
	/**
	 * @brief Finds a user by a case-insensitive username.
	 * @param username The login username.
	 * @return The user row or null.
	 */
	findByUsername(username: string): Promise<UserRow | null>;
	/**
	 * @brief Finds a user by email address.
	 * @param email The email to look up.
	 * @return The user row or null.
	 */
	findByEmail(email: string): Promise<UserRow | null>;
	/**
	 * @brief Finds a user by id.
	 * @param id The user id.
	 * @return The user row or null.
	 */
	findById(id: string): Promise<UserRow | null>;
	/**
	 * @brief Creates a user row.
	 * @param input The user fields (id generated by the caller).
	 * @return The created row.
	 */
	create(input: UserCreate): Promise<UserRow>;
	/** @brief Lists users with bounded pagination. @param limit Page size. @param offset Offset. @return Page. */
	listPage(limit: number, offset: number): Promise<{ items: UserRow[]; total: number }>;
	/** @brief Atomically changes credentials and revokes sessions. @param id Owner. @param currentHash Expected hash. @param newHash New hash. @return Whether changed. */
	changePassword(id: string, currentHash: string, newHash: string): Promise<boolean>;
	/** @brief Replaces an owner's recovery token. @param userId Owner. @param tokenHash Token digest. @param expiresAt Expiry. @return Completion. */
	createPasswordReset(userId: string, tokenHash: string, expiresAt: Date): Promise<void>;
	/** @brief Consumes a valid recovery token and revokes sessions. @param tokenHash Token digest. @param newHash New password hash. @param now Reference time. @return Whether reset. */
	resetPassword(tokenHash: string, newHash: string, now: Date): Promise<boolean>;
	/** @brief Applies admin-only changes, protecting the last admin. @param actorId Admin. @param id Target. @param patch Validated fields. @return Result. */
	manage(actorId: string, id: string, patch: UserPatch): Promise<UserRow | 'forbidden' | 'last_admin' | null>;
}

/** @brief Backward-compatible user creation with an optional login username. */
export type UserCreate = Omit<UserRow, 'createdAt' | 'username' | 'isActive' | 'sessionVersion'>
	& Partial<Pick<UserRow, 'username' | 'isActive' | 'sessionVersion'>>;

/** @brief Explicit administrator-editable fields; passwords require a separate operation. */
export interface UserPatch { role?: 'admin' | 'reader'; isActive?: boolean; }

/**
 * @brief Session persistence contract.
 */
export interface SessionRepository {
	/**
	 * @brief Stores a new session.
	 * @param input Session fields (token hash, user id, expiry).
	 * @return The created row.
	 */
	create(input: { id: string; tokenHash: string; userId: string; expiresAt: Date; userVersion?: number }): Promise<SessionRow>;
	/**
	 * @brief Finds a session by token hash with its user.
	 * @param tokenHash The SHA-256 hash of the presented token.
	 * @return The session plus user, or null.
	 */
	findByTokenHash(tokenHash: string): Promise<(SessionRow & { user: UserRow }) | null>;
	/**
	 * @brief Deletes the session matching a token hash.
	 * @param tokenHash The token hash to delete.
	 */
	deleteByTokenHash(tokenHash: string): Promise<void>;
	/**
	 * @brief Deletes every expired session.
	 * @param now The reference time.
	 * @return The number of deleted rows.
	 */
	deleteExpired(now: Date): Promise<number>;
}

/**
 * @brief A post row with its tag names attached.
 */
export interface PostWithTags extends PostRow {
	tags: string[];
}

/** @brief Optimistically checked image-reference replacement. */
export interface MediaReferencePatch {
	id: string;
	expectedUpdatedAt: Date;
	contentMarkdown: string;
	contentHtml: string;
	coverImage: string | null;
}

/** @brief Minimal administrator post projection for editor suggestions. */
export interface PostSuggestion {
	id: string;
	slug: string;
	title: string;
}

/**
 * @brief Writable creation fields with nullable groundwork fields defaulted.
 */
export type PostCreate = Omit<PostRow, 'createdAt' | 'updatedAt' | 'publishAt' | 'category' | 'searchVector'>
	& Partial<Pick<PostRow, 'publishAt' | 'category' | 'searchVector'>>;

/**
 * @brief Post persistence contract.
 */
export interface PostRepository {
	/**
	 * @brief Creates a post row.
	 * @param input The post fields (id generated by the caller).
	 * @return The created row.
	 */
	create(input: PostCreate): Promise<PostRow>;
	/**
	 * @brief Patches a post row and refreshes updatedAt.
	 * @param id The post id.
	 * @param patch Partial fields to overwrite.
	 * @return The updated row or null when missing.
	 */
	update(id: string, patch: Partial<PostRow>): Promise<PostRow | null>;
	/**
	 * @brief Atomically replaces image references if every post is unchanged.
	 * @param patches Expected versions and replacement content.
	 * @return False on a concurrent post change, without partial writes.
	 */
	updateMediaReferences(patches: MediaReferencePatch[]): Promise<boolean>;
	/**
	 * @brief Deletes a post row.
	 * @param id The post id.
	 * @return True when a row was deleted.
	 */
	remove(id: string): Promise<boolean>;
	/**
	 * @brief Finds a post by id.
	 * @param id The post id.
	 * @return The row or null.
	 */
	findById(id: string): Promise<PostRow | null>;
	/**
	 * @brief Finds a post by slug.
	 * @param slug The post slug.
	 * @return The row or null.
	 */
	findBySlug(slug: string): Promise<PostRow | null>;
	/**
	 * @brief Lists published posts, newest first, with pagination.
	 * @param options Page bounds, optional tag/search filters and reference time.
	 * @return The page items plus the total count.
	 */
	listPublished(options: {
		limit: number;
		offset: number;
		tag?: string | undefined;
		search?: string | undefined;
		now: Date;
	}): Promise<{ items: PostWithTags[]; total: number }>;
	/**
	 * @brief Lists every currently public post for graph construction.
	 * @param now The visibility reference time.
	 * @return Public rows with tag names.
	 */
	listGraph(now: Date): Promise<PostWithTags[]>;
	/**
	 * @brief Lists every post, newest first (admin view).
	 * @return All rows with tag names.
	 */
	listAll(): Promise<PostWithTags[]>;
	/**
	 * @brief Lists a bounded lightweight post index for editor suggestions.
	 * @param limit Maximum rows.
	 * @return Post identifiers, slugs and titles.
	 */
	listSuggestions(limit: number): Promise<PostSuggestion[]>;
	/**
	 * @brief Atomically publishes due drafts and clears their schedules.
	 * @param now The reference time.
	 * @return The number of published drafts.
	 */
	publishDue(now: Date): Promise<number>;
}

/**
 * @brief Tag persistence contract.
 */
export interface TagRepository {
	/**
	 * @brief Lists all tags ordered by name.
	 * @return The tag rows.
	 */
	list(): Promise<TagRow[]>;
	/**
	 * @brief Changes one tag color.
	 * @param id The tag id.
	 * @param color Validated HEX color.
	 * @return The updated row or null.
	 */
	updateColor(id: string, color: string): Promise<TagRow | null>;
	/**
	 * @brief Deletes a tag and every post association.
	 * @param id The tag id.
	 * @return Whether a tag was deleted.
	 */
	remove(id: string): Promise<boolean>;
	/**
	 * @brief Ensures one row per name (slugified), creating missing ones.
	 * @param names The tag names.
	 * @return The rows for all names.
	 */
	upsertByName(names: string[]): Promise<TagRow[]>;
	/**
	 * @brief Replaces the tag links of a post.
	 * @param postId The post id.
	 * @param tagIds The tag ids to link.
	 */
	setPostTags(postId: string, tagIds: string[]): Promise<void>;
	/**
	 * @brief Loads the tag names linked to a post.
	 * @param postId The post id.
	 * @return The linked tag names.
	 */
	getPostTagNames(postId: string): Promise<string[]>;
}

/**
 * @brief Comment persistence contract.
 */
export interface CommentRepository {
	/**
	 * @brief Creates a pending comment.
	 * @param input The comment fields (id generated by the caller).
	 * @return The created row.
	 */
	create(input: { id: string; postId: string; authorName: string; content: string }): Promise<CommentRow>;
	/**
	 * @brief Lists approved comments for a post, oldest first.
	 * @param postId The post id.
	 * @param offset The row offset, default zero.
	 * @return Up to 101 approved rows, including a pagination lookahead.
	 */
	listApproved(postId: string, offset?: number): Promise<CommentRow[]>;
	/**
	 * @brief Lists comments by status, newest first (admin view).
	 * @param status The status filter, if any.
	 * @param offset The row offset, default zero.
	 * @return Up to 101 matching rows, including a pagination lookahead.
	 */
	listByStatus(status?: CommentStatus, offset?: number): Promise<CommentRow[]>;
	/**
	 * @brief Changes a comment status.
	 * @param id The comment id.
	 * @param status The new status.
	 * @return The updated row or null.
	 */
	setStatus(id: string, status: CommentStatus): Promise<CommentRow | null>;
	/**
	 * @brief Deletes a comment.
	 * @param id The comment id.
	 * @return True when a row was deleted.
	 */
	remove(id: string): Promise<boolean>;
	/**
	 * @brief Counts pending comments.
	 * @return The pending count.
	 */
	countPending(): Promise<number>;
}

/**
 * @brief Like persistence contract.
 */
export interface LikeRepository {
	/**
	 * @brief Toggles a like for a voter hash.
	 * @param postId The post id.
	 * @param voterHash The anonymous voter hash.
	 * @return True when the post is now liked.
	 */
	toggle(postId: string, voterHash: string): Promise<boolean>;
	/**
	 * @brief Checks whether a voter likes a post.
	 * @param postId The post id.
	 * @param voterHash The anonymous voter hash.
	 * @return Whether the row exists.
	 */
	has(postId: string, voterHash: string): Promise<boolean>;
	/**
	 * @brief Counts likes for a post.
	 * @param postId The post id.
	 * @return The like count.
	 */
	count(postId: string): Promise<number>;
}

/**
 * @brief Page-view persistence contract (aggregates only, no personal data).
 */
export interface ViewRepository {
	/**
	 * @brief Records one view for a post on a day (upsert increment).
	 * @param postId The post id.
	 * @param day The UTC day string (YYYY-MM-DD).
	 */
	record(postId: string, day: string): Promise<void>;
	/**
	 * @brief Sums views per post since a day (inclusive).
	 * @param sinceDay The first UTC day string.
	 * @return Post ids with view totals, highest first.
	 */
	topSince(sinceDay: string): Promise<{ postId: string; views: number }[]>;
	/**
	 * @brief Sums all views since a day (inclusive).
	 * @param sinceDay The first UTC day string.
	 * @return The total view count.
	 */
	totalSince(sinceDay: string): Promise<number>;
}

/**
 * @brief Newsletter subscriber persistence contract.
 */
export interface SubscriberRepository {
	/**
	 * @brief Creates an unconfirmed subscriber.
	 * @param input Email plus token hash.
	 * @return The created row.
	 */
	create(input: { id: string; email: string; tokenHash: string }): Promise<SubscriberRow>;
	/**
	 * @brief Finds a subscriber by token hash.
	 * @param tokenHash The token hash.
	 * @return The row or null.
	 */
	findByTokenHash(tokenHash: string): Promise<SubscriberRow | null>;
	/**
	 * @brief Finds a subscriber by email.
	 * @param email The email address.
	 * @return The row or null.
	 */
	findByEmail(email: string): Promise<SubscriberRow | null>;
	/**
	 * @brief Marks a subscriber confirmed.
	 * @param id The subscriber id.
	 */
	confirm(id: string): Promise<void>;
	/**
	 * @brief Deletes a subscriber.
	 * @param id The subscriber id.
	 * @return True when a row was deleted.
	 */
	remove(id: string): Promise<boolean>;
	/**
	 * @brief Lists every subscriber ordered by creation (admin view).
	 * @return The rows.
	 */
	list(): Promise<SubscriberRow[]>;
	/**
	 * @brief Counts confirmed subscribers.
	 * @return The confirmed count.
	 */
	countConfirmed(): Promise<number>;
}

/**
 * @brief API token persistence contract.
 */
export interface TokenRepository {
	/**
	 * @brief Stores a token record (hash only, never the plain token).
	 * @param input The token fields.
	 * @return The created row.
	 */
	create(input: { id: string; userId: string; name: string; tokenHash: string; scope: TokenScope }): Promise<ApiTokenRow>;
	/**
	 * @brief Finds a token by hash with its owner.
	 * @param tokenHash The token hash.
	 * @return The token plus user, or null.
	 */
	findByTokenHash(tokenHash: string): Promise<(ApiTokenRow & { user: UserRow }) | null>;
	/**
	 * @brief Refreshes the last-used timestamp.
	 * @param id The token id.
	 */
	touch(id: string): Promise<void>;
	/**
	 * @brief Lists tokens with owners (admin view, hashes included for matching only).
	 * @return The rows with users.
	 */
	list(): Promise<(ApiTokenRow & { user: UserRow })[]>;
	/**
	 * @brief Revokes a token.
	 * @param id The token id.
	 * @return True when a row was deleted.
	 */
	revoke(id: string): Promise<boolean>;
}

/**
 * @brief Revision persistence contract.
 */
export interface RevisionRepository {
	/**
	 * @brief Stores a revision snapshot.
	 * @param input The snapshot fields.
	 * @return The created row.
	 */
	create(input: {
		id: string;
		postId: string;
		title: string;
		contentMarkdown: string;
		contentHtml: string;
	}): Promise<RevisionRow>;
	/**
	 * @brief Lists revisions for a post, newest first.
	 * @param postId The post id.
	 * @return The rows.
	 */
	listByPost(postId: string): Promise<RevisionRow[]>;
	/**
	 * @brief Finds one revision.
	 * @param id The revision id.
	 * @return The row or null.
	 */
	findById(id: string): Promise<RevisionRow | null>;
	/**
	 * @brief Deletes the oldest revisions beyond a keep limit.
	 * @param postId The post id.
	 * @param keep The number of newest revisions to keep.
	 */
	prune(postId: string, keep: number): Promise<void>;
}
